### ISSUE TITLE
Attempt to access memory outside buffer bounds

### ISSUE THREAD

**Issue by m4gpi** [Frando/kappa-sparse-indexer#4]
Attempting to run the tests in kappa-drive in master branch and this occurs frequently at different points. Logging this here for the moment, will dive a little deeper later.

```
internal/buffer.js:75
    throw new ERR_BUFFER_OUT_OF_BOUNDS();
    ^

RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to access memory outside buffer bounds
    at boundsError (internal/buffer.js:75:11)
    at Buffer.readUInt32BE (internal/buffer.js:300:5)
    at decodeInt (/shared/Projects/cobox-project/core/node_modules/kappa-sparse-indexer/lib/log.js:438:14)
    at Transform.transform [as _transform] (/shared/Projects/cobox-project/core/node_modules/kappa-sparse-indexer/lib/log.js:126:21)
    at Transform._read (_stream_transform.js:191:10)
    at Transform._write (_stream_transform.js:179:12)
    at doWrite (_stream_writable.js:403:12)
    at writeOrBuffer (_stream_writable.js:387:5)
    at Transform.Writable.write (_stream_writable.js:318:11)
    at ReadStream.ondata (/shared/Projects/cobox-project/core/node_modules/level-iterator-stream/node_modules/readable-stream/lib/_stream_readable.js:681:20) {
  code: 'ERR_BUFFER_OUT_OF_BOUNDS'
}
```

## Steps to Reproduce

```
git clone https://gitlab.com/coboxcoop/kappa-drive.git && cd kappa-drive
yarn
yarn test # repeat a few times until you see the error
```

**Comment by m4gpi** [comment]
this also occasionally occurs when running the [main cobox app](https://gitlab.com/coboxcoop/cobox-server), causing it to crash when starting.

@Frando have you encountered this issue in Sonar?

**Comment by Frando** [comment]
Thanks for opening this.

I ran into this issue once and suspected it was related to having data from a previous version of kappa-sparse-indexer in its leveldb. As it didn't occur again I didn't investigate.

I did a quick first debugging and its .. weird. I can reproduce with the kappa-drive tests and the weird thing is that it occurs sometimes, at seemingly random tests, and sometimes it just passes. *What seems to happen is the the [subleveldown](https://github.com/Level/subleveldown/) boundaries are not uphold*: kappa-sparse-indexer splits the leveldb in two parts, one for the materialized log and one to map all keys to ints. When the error occurs, the createReadStream method on the log gets a result row from the key index which it then cannot decode. This, I think, should not happen. Maybe subleveldown has issues with binary keys? (The key encoding is set to binary in kappa-sparse-index). I'll try to investigate further. One of the weirder bugs that is ;)

**Comment by Frando** [comment]
Just found this issue on subleveldown: [Possible issue with buffer keys #87](https://github.com/Level/subleveldown/issues/87).
It mentions two possible bugs/solutions:
* switch from `memdb` to `level-mem` which is more up-to-date and supported
* An issue with certain binary keys, see [this PR](https://github.com/Level/subleveldown/pull/88) that was merged and released in `subleveldown v5.0.0`

So first thing I'd do is trying if one of these or both together would fix the issue.

**Comment by Frando** [comment]
Ha, so I switched memdb to level-mem and now I cannot reproduce the error anymore. Here's a PR https://gitlab.com/coboxcoop/kappa-drive/-/merge_requests/3

@kyphae however if this also crashes cobox it's likely not the cause as there it wouldn't be memdb at all but subleveldown, right? Can you try switching to subleveldown 5.0.0 and see if that fixes it?

**Comment by m4gpi** [comment]
Nice, thanks! :fireworks:  I am using memdb for one useage in the server app, but not using indexer. I'll try this out locally and see if it works, and feed back.

**Comment by m4gpi** [comment]
have switched the stack over to `level-mem` and `subleveldown` and it no longer appears! :champagne: thanks a bunch @Frando :)

**Comment by m4gpi** [comment]
sadly, it's reappeared, but only when running the app. I've bumped subleveldown to v5 across the board, and removed all memdb instances. Tests all pass, doesn't crop up at all there. Leaving this open for now, will revisit next week. I've also tried bumping subleveldown in a fork of kappa-sparse-indexer and that hasn't helped.

**Comment by m4gpi** [comment]
to reproduce:

```
git clone --recursive https://gitlab.com/coboxcoop/core && cd core
git checkout memory-out-of-bounds
git submodule update --init --recursive
yarn test # all pass
./cobox client up # explodes
```

**Comment by m4gpi** [comment]
seems i needed to reset all indexes. whoops! :)
